### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by ashnair1**

### CODE REVIEW

**Comment by Ngoguey42** [comment]
I've activated readthedoc build on PRs: https://readthedocs.org/projects/buzzard/builds

**Comment by ashnair1** [comment]
> I've activated readthedoc build on PRs: https://readthedocs.org/projects/buzzard/builds

Thanks. There seems to be some issue with `gdal`. This will help with debugging.

**Comment by ashnair1** [comment]
@Ngoguey42 Can't seem to see the PR readthedocs builds.

The latest build I see is the latest commit to `master`

image

**Comment by Ngoguey42** [comment]
https://docs.readthedocs.io/en/stable/pull-requests.html says `We create and build a new version when a pull request is opened, and rebuild the version whenever a new commit is pushed.`

Can you try to close and open a new PR?

**Pull request closed without merging**
